feat: support run app by run.sh
douyu/jupiter-layout pull request #86
Opened 2023-02-08 02:11 UTC by B15030328

2023-02-10 08:41 UTC, hnlq715 requested changes

2023-02-10 08:41 UTC, hnlq715 commented on build/run.sh
> +pkgPath=${pwd//$GOPATH\/src\//}
这个脚本可以去掉

2023-02-10 08:41 UTC, hnlq715 commented on README.md
> +./build/run.sh config/exampleserver/local-live.toml 127.0.0.1 9999
可以直接给make -C 的使用方式

2023-02-14 08:57 UTC, B15030328 commented on build/run.sh
> +pkgPath=${pwd//$GOPATH\/src\//}
已去除多余脚本

2023-02-14 08:57 UTC, B15030328 commented on build/run.sh
> +pkgPath=${pwd//$GOPATH\/src\//}
已去除多余脚本

2023-02-15 08:33 UTC, hnlq715 approved these changes

2023-02-15 08:33 UTC, merged